services:
  postgres:
    image: postgres:17.5    
    environment:      
      POSTGRES_USER: calderarogustavo
      POSTGRES_PASSWORD: Gusang_20011
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - local-network
  pgadmin:
    image: dpage/pgadmin4:9.5
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: gucalderaro@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: Gusang_20011
    ports:
      - 8083:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - local-network
  kafka:
    image: bitnami/kafka:4.0
    ports:
      - 29092:9092
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9090,EXTERNAL://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9091
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
    volumes:
      - kafka-data:/bitnami/kafka
    networks:
      - local-network
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - 8085:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: service-kafka-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9090
    networks:
      - local-network    
  sonar:
    image: sonarqube:latest
    container_name: sonar
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"

volumes:
  postgres-data:
  pgadmin-data:
  kafka-data:  
networks:
  local-network:
    driver: bridge
